### ISSUE TITLE
View Menu hidden in firefox 6.0.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nth10sd/viewabout#6]
```
The view menu in version 6.0.2 is hidden, would it be possible to add it to the 
firefox menu, under options, web developer or on it's own?
```

Original issue reported on code.google.com by `gale.sk...@gmail.com` on 16 Sep 2011 at 9:42

**Comment by nth10sd** [comment]
If one turns on the default View menu by pressing "Alt" on Windows, one can see ViewAbout.

Works for me in latest ViewAbout 2.0.3: https://addons.mozilla.org/en-US/firefox/addon/viewabout/versions/2.0.3
