### ISSUE TITLE
Duplicate shortcut key in ViewAbout menu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nth10sd/viewabout#8]
```
What steps will reproduce the problem?
1. Install ViewAbout 2.x
2. Bring down the View menu
3. Note that "t" has two possible matches: "abou_t_:rights" and 
"abou_t_:support"

What is the expected output? What do you see instead?

You have to pick one of those

What version of the product are you using? On what operating system?

v2.0.1 on WinXP in SeaMonkey 2.9

Please provide any additional information below.

```

Original issue reported on code.google.com by `Tim.Poin...@gmail.com` on 27 Apr 2012 at 12:14

**Comment by nth10sd** [comment]
The bug is that "t" is the shortcut key for both [about:rights](https://github.com/nth10sd/viewabout/blob/master/locale/en-US/viewabout.dtd#L52) and [about:support](https://github.com/nth10sd/viewabout/blob/master/locale/en-US/viewabout.dtd#L63).
